/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ayyam8774
 */
public class frmMath extends javax.swing.JFrame {

    /**
     * Creates new form frmMath
     */
    public frmMath() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblDiscription1 = new javax.swing.JLabel();
        txtValue1a = new javax.swing.JTextField();
        txtValue1b = new javax.swing.JTextField();
        lblvs1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        lblAns1 = new javax.swing.JLabel();
        lblDiscription2 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        lblAns2 = new javax.swing.JLabel();
        lblDiscription3 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        lblAns3 = new javax.swing.JLabel();
        lblDiscription4 = new javax.swing.JLabel();
        btn4 = new javax.swing.JButton();
        lblAns4 = new javax.swing.JLabel();
        lblDiscription5 = new javax.swing.JLabel();
        txtValue5 = new javax.swing.JTextField();
        btn5 = new javax.swing.JButton();
        lblAns5 = new javax.swing.JLabel();
        lblDiscription6 = new javax.swing.JLabel();
        txtValue6 = new javax.swing.JTextField();
        btn6 = new javax.swing.JButton();
        lblAns6 = new javax.swing.JLabel();
        lblDiscription7 = new javax.swing.JLabel();
        txtValue7 = new javax.swing.JTextField();
        btn7 = new javax.swing.JButton();
        lblAns7 = new javax.swing.JLabel();
        lblDiscription8 = new javax.swing.JLabel();
        txtValue8 = new javax.swing.JTextField();
        btn8 = new javax.swing.JButton();
        lblAns8 = new javax.swing.JLabel();
        txtValue2a = new javax.swing.JTextField();
        txtValue2b = new javax.swing.JTextField();
        lblvs2 = new javax.swing.JLabel();
        txtValue3a = new javax.swing.JTextField();
        txtValue3b = new javax.swing.JTextField();
        lblvs3 = new javax.swing.JLabel();
        txtValue4a = new javax.swing.JTextField();
        txtValue4b = new javax.swing.JTextField();
        lblvs4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setText("Mystical Math Methods");
        lblTitle.setToolTipText("");

        lblDiscription1.setText("Enter two numbers and click the botton. The program will display the largest of the two numbers !!");

        txtValue1a.setText("  ");
        txtValue1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValue1aActionPerformed(evt);
            }
        });

        txtValue1b.setText("     ");
        txtValue1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValue1bActionPerformed(evt);
            }
        });

        lblvs1.setText("VS");

        btn1.setText("Largest →");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        lblAns1.setText("...");

        lblDiscription2.setText("Enter two numbers and click the button. The program will display the smallest of the two numbers !!");

        btn2.setText("Smallest →");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        lblAns2.setText("...");

        lblDiscription3.setText("Enter two numbers and click the button. The program will display the first number to the power of the second !!");

        btn3.setText("To the Power of →");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        lblAns3.setText("...");

        lblDiscription4.setText("Enter the length of two sides of a right angle triangle. The program will display the hypotenuse of the triangle !!");

        btn4.setText("Hypotenuse →");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        lblAns4.setText("...");

        lblDiscription5.setText("Enter a decimal value. The program will display the value rounded down to the nearest integer !!");

        txtValue5.setText("     ");

        btn5.setText("Rounded down  →");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        lblAns5.setText("...");

        lblDiscription6.setText("Enter a decimal value. The program will display the value rounded up to the nearest integer !!");

        txtValue6.setText("     ");

        btn6.setText("Rounded up  →");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        lblAns6.setText("...");

        lblDiscription7.setText("Enter the integer. The program will display the square root of the integer !!");

        txtValue7.setText("jTextField1");

        btn7.setText("Square Root →");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        lblAns7.setText("...");

        lblDiscription8.setText("Enter an ange in degrees. The program will display the angle in radians !!");

        txtValue8.setText("jTextField1");

        btn8.setText("In Radians →");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        lblAns8.setText("...");

        txtValue2a.setText("  ");
        txtValue2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValue2aActionPerformed(evt);
            }
        });

        txtValue2b.setText("     ");
        txtValue2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValue2bActionPerformed(evt);
            }
        });

        lblvs2.setText("VS");

        txtValue3a.setText("  ");
        txtValue3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValue3aActionPerformed(evt);
            }
        });

        txtValue3b.setText("     ");
        txtValue3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValue3bActionPerformed(evt);
            }
        });

        lblvs3.setText("VS");

        txtValue4a.setText("  ");
        txtValue4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValue4aActionPerformed(evt);
            }
        });

        txtValue4b.setText("     ");
        txtValue4b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValue4bActionPerformed(evt);
            }
        });

        lblvs4.setText("VS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(txtValue1a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblvs1)
                        .addGap(30, 30, 30)
                        .addComponent(txtValue1b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn1)
                        .addGap(18, 18, 18)
                        .addComponent(lblAns1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiscription1)
                            .addComponent(lblDiscription2)
                            .addComponent(lblDiscription3)
                            .addComponent(lblDiscription4)
                            .addComponent(lblDiscription5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(txtValue3a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblvs3)
                                .addGap(30, 30, 30)
                                .addComponent(txtValue3b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn3)
                                .addGap(18, 18, 18)
                                .addComponent(lblAns3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(txtValue4a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblvs4)
                                .addGap(30, 30, 30)
                                .addComponent(txtValue4b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btn4)
                                .addGap(18, 18, 18)
                                .addComponent(lblAns4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(txtValue5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btn5)
                                .addGap(33, 33, 33)
                                .addComponent(lblAns5))
                            .addComponent(lblDiscription6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(txtValue6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(btn6)
                                .addGap(33, 33, 33)
                                .addComponent(lblAns6))
                            .addComponent(lblDiscription7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiscription8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(txtValue8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95)
                                        .addComponent(btn8)
                                        .addGap(33, 33, 33)
                                        .addComponent(lblAns8)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(131, 131, 131)
                                    .addComponent(txtValue7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(95, 95, 95)
                                    .addComponent(btn7)
                                    .addGap(33, 33, 33)
                                    .addComponent(lblAns7)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(txtValue2a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblvs2)
                        .addGap(30, 30, 30)
                        .addComponent(txtValue2b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn2)
                        .addGap(18, 18, 18)
                        .addComponent(lblAns2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDiscription1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValue1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValue1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblvs1)
                    .addComponent(btn1)
                    .addComponent(lblAns1))
                .addGap(43, 43, 43)
                .addComponent(lblDiscription2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2)
                    .addComponent(lblAns2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValue2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValue2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblvs2)))
                .addGap(43, 43, 43)
                .addComponent(lblDiscription3)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAns3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValue3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValue3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblvs3)
                        .addComponent(btn3)))
                .addGap(43, 43, 43)
                .addComponent(lblDiscription4)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAns4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValue4a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValue4b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblvs4)
                        .addComponent(btn4)))
                .addGap(43, 43, 43)
                .addComponent(lblDiscription5)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValue5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5)
                    .addComponent(lblAns5))
                .addGap(43, 43, 43)
                .addComponent(lblDiscription6)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValue6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6)
                    .addComponent(lblAns6))
                .addGap(43, 43, 43)
                .addComponent(lblDiscription7)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValue7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7)
                    .addComponent(lblAns7))
                .addGap(43, 43, 43)
                .addComponent(lblDiscription8)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValue8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8)
                    .addComponent(lblAns8))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void txtValue1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValue1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValue1aActionPerformed

    private void txtValue1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValue1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValue1bActionPerformed

    private void txtValue2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValue2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValue2aActionPerformed

    private void txtValue2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValue2bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValue2bActionPerformed

    private void txtValue3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValue3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValue3aActionPerformed

    private void txtValue3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValue3bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValue3bActionPerformed

    private void txtValue4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValue4aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValue4aActionPerformed

    private void txtValue4bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValue4bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValue4bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JLabel lblAns1;
    private javax.swing.JLabel lblAns2;
    private javax.swing.JLabel lblAns3;
    private javax.swing.JLabel lblAns4;
    private javax.swing.JLabel lblAns5;
    private javax.swing.JLabel lblAns6;
    private javax.swing.JLabel lblAns7;
    private javax.swing.JLabel lblAns8;
    private javax.swing.JLabel lblDiscription1;
    private javax.swing.JLabel lblDiscription2;
    private javax.swing.JLabel lblDiscription3;
    private javax.swing.JLabel lblDiscription4;
    private javax.swing.JLabel lblDiscription5;
    private javax.swing.JLabel lblDiscription6;
    private javax.swing.JLabel lblDiscription7;
    private javax.swing.JLabel lblDiscription8;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblvs1;
    private javax.swing.JLabel lblvs2;
    private javax.swing.JLabel lblvs3;
    private javax.swing.JLabel lblvs4;
    private javax.swing.JTextField txtValue1a;
    private javax.swing.JTextField txtValue1b;
    private javax.swing.JTextField txtValue2a;
    private javax.swing.JTextField txtValue2b;
    private javax.swing.JTextField txtValue3a;
    private javax.swing.JTextField txtValue3b;
    private javax.swing.JTextField txtValue4a;
    private javax.swing.JTextField txtValue4b;
    private javax.swing.JTextField txtValue5;
    private javax.swing.JTextField txtValue6;
    private javax.swing.JTextField txtValue7;
    private javax.swing.JTextField txtValue8;
    // End of variables declaration//GEN-END:variables
}
